### ISSUE TITLE
[Question] Activation function used in EfficientNet Backbone

### ISSUE THREAD

**Issue by goutambhat** [ViswanathaReddyGajjala/EfficientNet-RetinaNet#8]
Hi, 
Can you please tell me the activation function used in the EfficientNet Backbone, i could not find any activation function being used.
Please correct me if I am wrong. 

If any activation function is being used, can you point me the piece of code.

Thanks.

**Comment by ViswanathaReddyGajjala** [comment]
In the backbone network swish activation function is being used. Please have a look at the following links:  [link1](https://github.com/ViswanathaReddyGajjala/EfficientNet-RetinaNet/blob/master/efficientnet_model.py#L102) and [link2](https://github.com/ViswanathaReddyGajjala/EfficientNet-RetinaNet/blob/e7480bcabc354dbc0bf652a1e33924c077a5a4db/efficientnet_utils.py#L61).

**Comment by goutambhat** [comment]
When i do a print of network, i could not see any activation layer being printed.
So swish activation is used only for SE layer not for any other Conv layer?

**Comment by ViswanathaReddyGajjala** [comment]
If you print a network, it only shows the layers that are initialized in the __init__ function. You must debug the code in order to know about all of the layers that are being used. You may also inspect the network graph using Netron. I personally recommend the second method for your use case.

**Comment by goutambhat** [comment]
Thanks a lot for your suggestions and very quick support. I will debug the code and also visualize the network using Netron.
